### ISSUE TITLE
Issues running tests

### ISSUE THREAD

**Issue by mstiehm-NF** [NVIDIA-ISAAC-ROS/isaac_ros_benchmark#5]
We are unable to run any of the tests in either the isaac or the ros2 benchmark packages.
This is the error we get.
```
.../workspaces/isaac_ros-dev$ launch_test src/isaac_ros_benchmark/scripts/isaac_ros_apriltag_node.py


...
[INFO] [1691780700.645765362] [r2b.Controller.Loading]:  - File hash = "5e8f11201fe10dbac7307a8628553e94"
[INFO] [1691780700.647126819] [r2b.Controller.Loading]:  - File size (bytes) = 3087908864
[INFO] [1691780700.706263151] [r2b.Controller.Loading]: Requesting to initialize the data loader node
[component_container_mt-1] [INFO] [1691780700.707784742] [r2b.DataLoaderNode]: Set the rosbag file to be: /workspaces/isaac_ros-dev/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage
[component_container_mt-1] [ERROR] [1691780700.715665217] [r2b.DataLoaderNode]: Failed to open the rosbag: Exception on parsing info file: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
FAIL

======================================================================
FAIL: test_benchmark (isaac_ros_apriltag_node.TestIsaacROSAprilTagNode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/isaac_ros-dev/src/isaac_ros_benchmark/scripts/isaac_ros_apriltag_node.py", line 148, in test_benchmark
    self.run_benchmark()
  File "/workspaces/isaac_ros-dev/install/ros2_benchmark/lib/python3.8/site-packages/ros2_benchmark/ros2_benchmark_test.py", line 852, in run_benchmark
    self.prepare_buffer()
  File "/workspaces/isaac_ros-dev/install/ros2_benchmark/lib/python3.8/site-packages/ros2_benchmark/ros2_benchmark_test.py", line 489, in prepare_buffer
    self.get_service_response_from_future_blocking(
  File "/workspaces/isaac_ros-dev/install/ros2_benchmark/lib/python3.8/site-packages/ros2_benchmark/ros2_benchmark_test.py", line 429, in get_service_response_from_future_blocking
    self.fail('A service returned with an unsuccess response')
AssertionError: A service returned with an unsuccess response
```

**Comment by jaiveersinghNV** [comment]
Could you verify that the rosbag at the path `/workspaces/isaac_ros-dev/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage` exists?

Could you run `ros2 bag info /workspaces/isaac_ros-dev/src/ros2_benchmark/assets/datasets/r2b_dataset/r2b_storage` and provide the result?

Instructions for downloading the rosbag datasets used for benchmarking are available [here](https://github.com/NVIDIA-ISAAC-ROS/ros2_benchmark#datasets).
